User tinyproxy
Group tinyproxy
Port 8888
Listen 0.0.0.0
Timeout 60
MaxClients 50
Allow 0.0.0.0/0
ConnectPort 443
PidFile "/tmp/tinyproxy.pid"
Filter "/etc/tinyproxy/filter"
FilterType ere
FilterDefaultDeny Yes
FilterURLs Off
LogLevel Connect
DisableViaHeader Yes
