"""Self-owned stateful trendline-family model contracts and configuration."""

from .config import MTFConfig, RailsConfig, ResolvedTrendlineFamilyConfig, TrendlineFamilyConfig
from .contracts import (
    FamilyCorridor,
    FamilyInteractionObservation,
    FamilyInteractionEvent,
    FamilyInteractionEventTransition,
    InteractionEventState,
    InteractionCompatibilityLabel,
    InteractionObservationState,
    FamilyRailProjection,
    FamilySourceGroupAudit,
    TrendlineFamilyOutput,
    TrendlineFamilySnapshot,
    compute_trendline_family_snapshot_id,
    trendline_family_snapshot_identity_payload,
    trendline_family_snapshot_has_phase_g_evidence,
    validate_trendline_family_snapshot_identity,
)
from .api import compose_trendline_family_mtf, update_trendline_families
from .fitting import PathfindingLineFitter
from .pivots import CausalFractalPivotExtractor
from .provider import NativeDeterministicLineProvider
from .repository import InMemoryTrendlineFamilyRepository, TrendlineFamilyRepository
from .registry import get_line_provider
from .tracker import TrendlineFamilyTracker
from .mtf import (
    LatestMTFSnapshotStore,
    MTFCluster,
    MTFGeometrySnapshot,
    MTFFreshnessState,
    MTFNormalizationContext,
    MTFPolicyAudit,
    MTFRelation,
    MTFRelationType,
    MTFSourceSnapshotAudit,
    MTFSourceSnapshotReference,
    MTFSourceStatus,
    ProjectedMTFFamily,
    ProjectedMTFMember,
    build_mtf_shadow_features,
    compose_mtf_snapshot,
    compute_mtf_snapshot_id,
    deserialize_mtf_snapshot,
    serialize_mtf_snapshot,
)

__all__ = [
    "InMemoryTrendlineFamilyRepository",
    "CausalFractalPivotExtractor",
    "FamilyCorridor",
    "FamilyInteractionObservation",
    "FamilyInteractionEvent",
    "FamilyInteractionEventTransition",
    "InteractionEventState",
    "InteractionCompatibilityLabel",
    "InteractionObservationState",
    "FamilyRailProjection",
    "FamilySourceGroupAudit",
    "compute_trendline_family_snapshot_id",
    "NativeDeterministicLineProvider",
    "PathfindingLineFitter",
    "ResolvedTrendlineFamilyConfig",
    "MTFConfig",
    "RailsConfig",
    "TrendlineFamilyConfig",
    "TrendlineFamilyOutput",
    "TrendlineFamilyRepository",
    "TrendlineFamilySnapshot",
    "TrendlineFamilyTracker",
    "get_line_provider",
    "update_trendline_families",
    "compose_trendline_family_mtf",
    "trendline_family_snapshot_identity_payload",
    "trendline_family_snapshot_has_phase_g_evidence",
    "validate_trendline_family_snapshot_identity",
    "LatestMTFSnapshotStore",
    "MTFCluster",
    "MTFGeometrySnapshot",
    "MTFFreshnessState",
    "MTFNormalizationContext",
    "MTFPolicyAudit",
    "MTFRelation",
    "MTFRelationType",
    "MTFSourceSnapshotAudit",
    "MTFSourceSnapshotReference",
    "MTFSourceStatus",
    "ProjectedMTFFamily",
    "ProjectedMTFMember",
    "build_mtf_shadow_features",
    "compose_mtf_snapshot",
    "compute_mtf_snapshot_id",
    "deserialize_mtf_snapshot",
    "serialize_mtf_snapshot",
]
