features:
  assets:
    BTCUSDT:
      timeframes:
        15m:
          RSI:
            period: 21
        1h:
          MACD:
            fast_period: 12
            signal_period: 9
            slow_period: 26
          RSI:
            period: 14
    ETHUSDT:
      timeframes:
        1h:
          RSI:
            period: 12
    default:
      timeframes:
        default:
          BollingerBands:
            period: 20
            num_std: 2.0
          EMA:
            period: 20
          MACD:
            fast_period: 12
            signal_period: 9
            slow_period: 26
          RSI:
            period: 14
